pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo $WORKSPACE'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
      }
}