pipeline {
    agent any
    environment {
        pass = credentials('ansible')
    }
    stages {
        stage('deploy kubernetes cluster') {
            steps {
                sh 'cd $WORKSPACE/ansible-c/kubernetes-setup'
                sh 'ansible-playbook -i ${WORKSPACE}/ansible-c/kubernetes-setup/hosts ${WORKSPACE}/ansible-c/kubernetes-setup/k8s-setup.yaml'
            }
        }
      }
}