pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        //pass = credentials('ansible')
        PLAY_PATH = "${WORKSPACE}/ansible-c/kubernetes-setup" 
    }
    stages {
        stage('checkout') {
            steps {
                checkOut()
            }
        }
        stage('display variable') {
            steps {
                display()
            }
        }
        stage('deploy kubernetes cluster') {
            steps {
                deploy()
            }
        }
      }
      post {
        always {
            echo 'Print Always'
            
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            
        }
    }
}



// display

def display() {
    sh 'echo ${PLAY_PATH}'
}

// checkout

def checkOut() {
    git credentialsId: 'github', url: 'https://github.com/teachdops/jenkins.git'
}
// deploy

def deploy() {

    ansiblePlaybook become: true, becomeUser: null, credentialsId: 'ansiblewithkey', disableHostKeyChecking: true, installation: 'ansible', inventory: '${PLAY_PATH}/hosts', playbook: '${PLAY_PATH}/k8s-setup.yaml'
}